baseURL = "https://radu.netlify.app"
languageCode = "en-us"
title = "Radu Ciurca"
theme = "kube"
description = "Radu Ciurca | Blog | Notes and more"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Radu Ciurca" # add your company name
  github = "ciurca" # add your github profile name
  twitter = "raduciurca" # add your twitter profile
  email = "raduciurca@gmail.com"
  

[[menu.main]]
    name = "Blog"
    weight = -120
    url = "/blog/"

[[menu.main]]
    name = "Technica"
    weight = -110
    url = "/technica/"

[[menu.extra]]
    name = "Home"
    weight = -100
    url = "/"
